In [8]:
import torch

In [24]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [25]:
x_data

tensor([[1, 2],
        [3, 4]])

In [26]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [27]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.7184, 0.4546],
        [0.6256, 0.8622]]) 



In [28]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4764, 0.0981, 0.9975],
        [0.6373, 0.5646, 0.2158]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [29]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [30]:
# Standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)
print(f"Tensor original: {tensor}")

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

print()
tensor[:,1] = 0
print(tensor, "after setting second column to zero")

Tensor original: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) after setting second column to zero


In [31]:
# Joining tensors You can use torch.cat to concatenate a sequence of tensors
# along a given dimension.
# See also torch.stack, another tensor joining operator
# that is subtly different from torch.cat.

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [32]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [33]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [34]:
x1 = torch.tensor([[1,1], [1,1]])
x2 = torch.tensor([[2,2], [2,2]])

print(x1 @ x2)

tensor([[4, 4],
        [4, 4]])


In [35]:
x1 = torch.tensor([[1,6],
                   [7,4]])
x2 = torch.tensor([[1,0],
                   [8,8]])

print(x1 @ x2)

tensor([[49, 48],
        [39, 32]])


In [36]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [37]:
#In-place operations Operations that store the result into the operand
# are called in-place. They are denoted
# by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [9]:
# Method 1: Direct boolean tensor
mask1 = torch.tensor([True, False, True])

# Method 2: Comparison operations (most common)
tensor = torch.tensor([1, 2, 3, 4, 5])
mask2 = tensor > 3  # [False, False, False, True, True]

# Method 3: Logical operations
mask3 = (tensor > 2) & (tensor < 5)  # AND: [False, False, True, True, False]
mask4 = (tensor < 2) | (tensor > 4)  # OR:  [True, False, False, False, True]
mask5 = ~(tensor == 3)               # NOT: [True, True, False, True, True]

In [10]:
mask2

tensor([False, False, False,  True,  True])

In [4]:
mask3

tensor([False, False,  True,  True, False])

In [5]:
tensor[mask3]

tensor([3, 4])

In [6]:
torch.randperm(2000)[:10]

tensor([1595,  497,  824, 1726,  280, 1226,  605, 1273, 1693, 1287])

In [7]:
tensor = torch.arange(10)
torch.clamp(tensor, min=2, max=4)

tensor([2, 2, 2, 3, 4, 4, 4, 4, 4, 4])

In [4]:
x = torch.tensor([1, 2, 3, 4])

In [5]:
torch.unsqueeze(x, 0)  # Add a new dimension at the 0th position

tensor([[1, 2, 3, 4]])

In [6]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
torch.unsqueeze(x, 2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [13]:
# torch.nonzero() returns the indices of
# all non-zero elements in a tensor.
# It's extremely useful for finding where specific conditions
# are met in your data.
tensor_1d = torch.tensor([0, 5, 0, 3, 0, 8])
torch.nonzero(tensor_1d)

# tensor([[1],
#         [3],
#         [5]])
# Meaning: elements at positions 1, 3, and 5 are non-zero

tensor([[1],
        [3],
        [5]])

In [ ]:
tensor_2d = torch.tensor([[0, 1, 0],
                       [2, 0, 3],
                       [0, 0, 4]])
torch.nonzero(tensor_2d)

# tensor([[0, 1],  # Row 0, Column 1 (value: 1)
#         [1, 0],  # Row 1, Column 0 (value: 2)
#         [1, 2],  # Row 1, Column 2 (value: 3)
#         [2, 2]]) # Row 2, Column 2 (value: 4)

tensor([[0, 1],
        [1, 0],
        [1, 2],
        [2, 2]])

In [38]:
# Check if MPS is available
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Using Apple Silicon GPU (MPS)")
else:
    device = torch.device("cpu")

Using Apple Silicon GPU (MPS)


In [39]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    print(f"Moving tensor to {torch.accelerator.current_accelerator()}")
    tensor = tensor.to(torch.accelerator.current_accelerator())

Moving tensor to mps


In [40]:
import torch
import numpy as np
import time

def benchmark_operation(sizes, device='mps'):
    results = {'numpy': [], 'pytorch': []}
    
    for N in sizes:
        # NumPy version
        pos_np = np.random.rand(N, 2).astype(np.float32)
        
        t0 = time.perf_counter()
        for _ in range(10):  # Average over runs
            dx = pos_np[:, 0][:, None] - pos_np[:, 0][None, :]
            dy = pos_np[:, 1][:, None] - pos_np[:, 1][None, :]
            dist = np.sqrt(dx**2 + dy**2)
        numpy_time = (time.perf_counter() - t0) / 10
        results['numpy'].append(numpy_time)
        
        # PyTorch version
        pos_torch = torch.from_numpy(pos_np).to(device)
        
        # Warmup (important for GPU!)
        for _ in range(3):
            dist = torch.cdist(pos_torch, pos_torch)
        
        t0 = time.perf_counter()
        for _ in range(10):
            dist = torch.cdist(pos_torch, pos_torch)
            torch.cuda.synchronize() if device=='cuda' else None
        pytorch_time = (time.perf_counter() - t0) / 10
        results['pytorch'].append(pytorch_time)
        
        speedup = numpy_time / pytorch_time
        print(f"N={N:5d}: NumPy={numpy_time*1000:6.1f}ms, "
              f"PyTorch={pytorch_time*1000:6.1f}ms, "
              f"Speedup={speedup:.2f}x")
    
    return results

# Run benchmark
sizes = [500, 1000, 2000, 3000, 5000, 7000, 10000, 15000, 20000]
results = benchmark_operation(sizes, device='mps')  # or 'cuda'

N=  500: NumPy=   0.6ms, PyTorch=   0.2ms, Speedup=3.15x
N= 1000: NumPy=   2.5ms, PyTorch=   0.2ms, Speedup=10.13x
N= 2000: NumPy=   8.1ms, PyTorch=   0.2ms, Speedup=33.49x
N= 3000: NumPy=  37.9ms, PyTorch=   0.2ms, Speedup=182.71x
N= 5000: NumPy=  59.2ms, PyTorch=   0.2ms, Speedup=292.10x
N= 7000: NumPy= 141.2ms, PyTorch=   0.2ms, Speedup=573.57x
N=10000: NumPy= 270.5ms, PyTorch=   0.2ms, Speedup=1319.62x
N=15000: NumPy= 842.4ms, PyTorch=   0.3ms, Speedup=3016.87x
N=20000: NumPy=1559.3ms, PyTorch=   0.3ms, Speedup=4612.82x
